var searchData=
[
  ['s_20method_0',['Danilevsky&apos;s Method',['../Danilevsky.html',1,'md_docs_2pages_2Notes_2Introduction']]],
  ['sample_20layout_1',['Sample Layout',['../md_docs_2pages_2BitStore.html#sample-layout',1,'']]],
  ['search_2',['Search',['../md_docs_2pages_2Unsigned.html#search',1,'']]],
  ['see_20also_3',['See Also',['../md_docs_2pages_2BitStore.html#see-also',1,'See Also'],['../md_docs_2pages_2BitArray.html#see-also-1',1,'See Also'],['../md_docs_2pages_2BitVec.html#see-also-2',1,'See Also'],['../md_docs_2pages_2BitSpan.html#see-also-3',1,'See Also'],['../md_docs_2pages_2BitRef.html#see-also-4',1,'See Also'],['../md_docs_2pages_2BitPoly.html#see-also-5',1,'See Also'],['../md_docs_2pages_2BitMat.html#see-also-6',1,'See Also'],['../md_docs_2pages_2BitGauss.html#see-also-7',1,'See Also'],['../md_docs_2pages_2BitLU.html#see-also-8',1,'See Also'],['../md_docs_2pages_2Iterators.html#see-also-9',1,'See Also'],['../md_docs_2pages_2assert.html#see-also-10',1,'See Also']]],
  ['set_20unset_20bit_20indices_4',['Set Unset Bit Indices',['../md_docs_2pages_2BitStore.html#store-indices',1,'Set/Unset Bit Indices'],['../md_docs_2pages_2BitArray.html#set-indices',1,'Set/Unset Bit Indices'],['../md_docs_2pages_2BitVec.html#vec-indices',1,'Set/Unset Bit Indices'],['../md_docs_2pages_2BitSpan.html#span-indices',1,'Set/Unset Bit Indices']]],
  ['shifts_5',['Bit Shifts',['../md_docs_2pages_2BitStore.html#bit-shifts',1,'']]],
  ['simple_20example_6',['Simple Example',['../index.html#a-simple-example',1,'A Simple Example'],['../md_docs_2pages_2BitGauss.html#a-simple-example-1',1,'A Simple Example']]],
  ['simplifications_20in_200_7',['Simplifications in \\(\\mathbb{F}_2\\)',['../GF2.html#simplifications-in-fmathbbf_2f',1,'']]],
  ['size_20and_20type_20queries_8',['Size and Type Queries',['../md_docs_2pages_2BitMat.html#size-and-type-queries',1,'']]],
  ['solution_20access_9',['Solution Access',['../md_docs_2pages_2BitGauss.html#solution-access',1,'']]],
  ['solutions_10',['Multiple Solutions',['../md_docs_2pages_2BitGauss.html#multiple-solutions',1,'']]],
  ['solver_11',['The &lt;span class=&quot;tt&quot;&gt;BitGauss&lt;/span&gt; Solver',['../md_docs_2pages_2BitGauss.html',1,'']]],
  ['solvers_12',['Linear System Solvers',['../md_docs_2pages_2BitMat.html#linear-system-solvers',1,'']]],
  ['solving_13',['Linear System Solving',['../md_docs_2pages_2BitLU.html#linear-system-solving',1,'']]],
  ['spans_14',['Spans',['../md_docs_2pages_2BitStore.html#store-spans',1,'Spans'],['../md_docs_2pages_2BitArray.html#set-span',1,'Spans'],['../md_docs_2pages_2BitVec.html#vec-span',1,'Spans'],['../md_docs_2pages_2BitSpan.html#span-span',1,'Spans']]],
  ['spans_15',['Bit-spans',['../md_docs_2pages_2BitStore.html#bit-spans',1,'']]],
  ['special_20matrices_16',['Special Matrices',['../md_docs_2pages_2BitMat.html#special-matrices',1,'']]],
  ['square_20step_17',['The Square Step',['../Reduction.html#the-square-step',1,'']]],
  ['square_20technique_18',['A Multiply &amp;amp; Square Technique',['../Reduction.html#a-multiply--square-technique',1,'']]],
  ['standard_20versions_19',['The &quot;Standard&quot; Versions',['../md_docs_2pages_2assert.html#the-standard-versions',1,'']]],
  ['step_20',['Step',['../Reduction.html#the-multiply-step',1,'The Multiply Step'],['../Reduction.html#the-square-step',1,'The Square Step']]],
  ['string_20encoding_21',['String Encoding',['../md_docs_2pages_2BitStore.html#binary-string-encoding',1,'Binary String Encoding'],['../md_docs_2pages_2BitStore.html#hex-string-encoding',1,'Hex String Encoding']]],
  ['string_20encodings_22',['String Encodings',['../md_docs_2pages_2BitStore.html#string-encodings',1,'']]],
  ['string_20functions_23',['Utility String Functions',['../md_docs_2pages_2BitMat.html#utility-string-functions',1,'']]],
  ['stringification_24',['Stringification',['../md_docs_2pages_2BitStore.html#store-stringification',1,'Stringification'],['../md_docs_2pages_2BitArray.html#set-stringification',1,'Stringification'],['../md_docs_2pages_2BitVec.html#vec-stringification',1,'Stringification'],['../md_docs_2pages_2BitSpan.html#span-stringification',1,'Stringification'],['../md_docs_2pages_2BitPoly.html#stringification',1,'Stringification'],['../md_docs_2pages_2BitMat.html#stringification-1',1,'Stringification'],['../md_docs_2pages_2Unsigned.html#stringification-2',1,'Stringification']]],
  ['strings_25',['Strings',['../md_docs_2pages_2BitVec.html#vec-strings',1,'Construction from Strings'],['../md_docs_2pages_2BitMat.html#from-strings',1,'From Strings']]],
  ['sub_20matrices_26',['Sub Matrices',['../md_docs_2pages_2BitMat.html#sub-matrices',1,'Sub-Matrices'],['../md_docs_2pages_2BitMat.html#triangular-sub-matrices',1,'Triangular Sub-Matrices']]],
  ['sub_20vectors_27',['Sub vectors',['../md_docs_2pages_2BitStore.html#store-sub-vectors',1,'Sub-vectors'],['../md_docs_2pages_2BitArray.html#set-sub-vectors',1,'Sub-vectors'],['../md_docs_2pages_2BitVec.html#vec-sub-vectors',1,'Sub-vectors'],['../md_docs_2pages_2BitSpan.html#span-sub-vectors',1,'Sub-vectors']]],
  ['summary_28',['Summary',['../Reduction.html#summary',1,'']]],
  ['system_20solvers_29',['Linear System Solvers',['../md_docs_2pages_2BitMat.html#linear-system-solvers',1,'']]],
  ['system_20solving_30',['Linear System Solving',['../md_docs_2pages_2BitLU.html#linear-system-solving',1,'']]]
];
