var searchData=
[
  ['s_20method_0',['Danilevsky&apos;s Method',['../Danilevsky.html',1,'md_docs_2pages_2Notes_2Introduction']]],
  ['sample_20layout_1',['Sample Layout',['../md_docs_2pages_2BitStore.html#sample-layout',1,'']]],
  ['search_2',['Search',['../md_docs_2pages_2Unsigned.html#search',1,'']]],
  ['see_20also_3',['See Also',['../md_docs_2pages_2BitStore.html#see-also',1,'See Also'],['../md_docs_2pages_2BitSet.html#see-also-1',1,'See Also'],['../md_docs_2pages_2BitVec.html#see-also-2',1,'See Also'],['../md_docs_2pages_2BitSpan.html#see-also-3',1,'See Also'],['../md_docs_2pages_2BitRef.html#see-also-4',1,'See Also'],['../md_docs_2pages_2BitPoly.html#see-also-5',1,'See Also'],['../md_docs_2pages_2BitMat.html#see-also-6',1,'See Also'],['../md_docs_2pages_2BitGauss.html#see-also-7',1,'See Also'],['../md_docs_2pages_2BitLU.html#see-also-8',1,'See Also'],['../md_docs_2pages_2Iterators.html#see-also-9',1,'See Also'],['../md_docs_2pages_2assert.html#see-also-10',1,'See Also']]],
  ['set_20fillers_4',['Bit-set Fillers',['../md_docs_2pages_2BitSet.html#set-fillers',1,'']]],
  ['set_20mutators_5',['Bit-set Mutators',['../md_docs_2pages_2BitSet.html#set-mutators',1,'']]],
  ['set_20queries_6',['Bit-set Queries',['../md_docs_2pages_2BitSet.html#set-queries',1,'']]],
  ['set_20unset_20bit_20indices_7',['Set Unset Bit Indices',['../md_docs_2pages_2BitStore.html#store-indices',1,'Set/Unset Bit Indices'],['../md_docs_2pages_2BitSet.html#set-indices',1,'Set/Unset Bit Indices'],['../md_docs_2pages_2BitVec.html#vec-indices',1,'Set/Unset Bit Indices'],['../md_docs_2pages_2BitSpan.html#span-indices',1,'Set/Unset Bit Indices']]],
  ['shifts_8',['Bit Shifts',['../md_docs_2pages_2BitStore.html#bit-shifts',1,'']]],
  ['simple_20example_9',['Simple Example',['../index.html#a-simple-example',1,'A Simple Example'],['../md_docs_2pages_2BitGauss.html#a-simple-example-1',1,'A Simple Example']]],
  ['simplifications_20in_200_10',['Simplifications in \\(\\mathbb{F}_2\\)',['../GF2.html#simplifications-in-fmathbbf_2f',1,'']]],
  ['size_20and_20type_11',['Size and Type',['../md_docs_2pages_2BitMat.html#size-and-type',1,'']]],
  ['solution_20access_12',['Solution Access',['../md_docs_2pages_2BitGauss.html#solution-access',1,'']]],
  ['solutions_13',['Multiple Solutions',['../md_docs_2pages_2BitGauss.html#multiple-solutions',1,'']]],
  ['solver_14',['The &lt;span class=&quot;tt&quot;&gt;BitGauss&lt;/span&gt; Solver',['../md_docs_2pages_2BitGauss.html',1,'']]],
  ['solvers_15',['Linear System Solvers',['../md_docs_2pages_2BitMat.html#linear-system-solvers',1,'']]],
  ['solving_16',['Linear System Solving',['../md_docs_2pages_2BitLU.html#linear-system-solving',1,'']]],
  ['span_20creators_17',['Span Creators',['../md_docs_2pages_2BitStore.html#store-spans',1,'Span Creators'],['../md_docs_2pages_2BitSet.html#set-span',1,'Span Creators'],['../md_docs_2pages_2BitVec.html#vec-span',1,'Span Creators'],['../md_docs_2pages_2BitSpan.html#span-span',1,'Span Creators']]],
  ['span_20fillers_18',['Span Fillers',['../md_docs_2pages_2BitSpan.html#span-fillers',1,'']]],
  ['span_20mutators_19',['Span Mutators',['../md_docs_2pages_2BitSpan.html#span-mutators',1,'']]],
  ['span_20queries_20',['Span Queries',['../md_docs_2pages_2BitSpan.html#span-queries',1,'']]],
  ['spans_21',['Bit-spans',['../md_docs_2pages_2BitStore.html#bit-spans',1,'']]],
  ['special_20matrices_22',['Special Matrices',['../md_docs_2pages_2BitMat.html#special-matrices',1,'']]],
  ['square_20step_23',['The Square Step',['../Reduction.html#the-square-step',1,'']]],
  ['square_20technique_24',['A Multiply &amp;amp; Square Technique',['../Reduction.html#a-multiply--square-technique',1,'']]],
  ['standard_20versions_25',['The &quot;Standard&quot; Versions',['../md_docs_2pages_2assert.html#the-standard-versions',1,'']]],
  ['step_26',['Step',['../Reduction.html#the-multiply-step',1,'The Multiply Step'],['../Reduction.html#the-square-step',1,'The Square Step']]],
  ['store_20fillers_27',['Store Fillers',['../md_docs_2pages_2BitStore.html#store-fillers',1,'']]],
  ['store_20mutators_28',['Store Mutators',['../md_docs_2pages_2BitStore.html#store-mutators',1,'']]],
  ['store_20queries_29',['Store Queries',['../md_docs_2pages_2BitStore.html#store-queries',1,'']]],
  ['string_20encoding_30',['String Encoding',['../md_docs_2pages_2BitStore.html#binary-string-encoding',1,'Binary String Encoding'],['../md_docs_2pages_2BitStore.html#hex-string-encoding',1,'Hex String Encoding']]],
  ['string_20encodings_31',['String Encodings',['../md_docs_2pages_2BitStore.html#string-encodings',1,'']]],
  ['string_20methods_32',['Utility String Methods',['../md_docs_2pages_2BitMat.html#utility-string-methods',1,'']]],
  ['stringification_33',['Stringification',['../md_docs_2pages_2BitStore.html#tore-stringification',1,'Stringification'],['../md_docs_2pages_2BitSet.html#set-stringification',1,'Stringification'],['../md_docs_2pages_2BitVec.html#vec-stringification',1,'Stringification'],['../md_docs_2pages_2BitSpan.html#span-stringification',1,'Stringification'],['../md_docs_2pages_2BitPoly.html#stringification',1,'Stringification'],['../md_docs_2pages_2BitMat.html#stringification-1',1,'Stringification'],['../md_docs_2pages_2Unsigned.html#stringification-2',1,'Stringification']]],
  ['strings_34',['Strings',['../md_docs_2pages_2BitVec.html#vec-strings',1,'Construction from Strings'],['../md_docs_2pages_2BitMat.html#construction-from-strings',1,'Construction from Strings']]],
  ['sub_20matrices_35',['Sub Matrices',['../md_docs_2pages_2BitMat.html#sub-matrices',1,'Sub-Matrices'],['../md_docs_2pages_2BitMat.html#triangular-sub-matrices',1,'Triangular Sub-Matrices']]],
  ['sub_20vector_20extractors_36',['Sub vector Extractors',['../md_docs_2pages_2BitStore.html#store-sub-vectors',1,'Sub-vector Extractors'],['../md_docs_2pages_2BitSet.html#set-sub-vectors',1,'Sub-vector Extractors'],['../md_docs_2pages_2BitVec.html#vec-sub-vectors',1,'Sub-vector Extractors'],['../md_docs_2pages_2BitSpan.html#span-sub-vectors',1,'Sub-vector Extractors']]],
  ['summary_37',['Summary',['../Reduction.html#summary',1,'']]],
  ['system_20solvers_38',['Linear System Solvers',['../md_docs_2pages_2BitMat.html#linear-system-solvers',1,'']]],
  ['system_20solving_39',['Linear System Solving',['../md_docs_2pages_2BitLU.html#linear-system-solving',1,'']]]
];
