// This file was generated by running the script `doxytest.py` to extract tests from comments in input files.
// Input file(s): `store_word.h`
// Do not edit this file manually -- it may be overwritten.
// Generated on: 2025-11-30 15:49:37

#include "../include/gf2/store_word.h"
#include <print>

int main() {
    std::println(stderr, "No test cases were found in `store_word.h`.");
}