// This file was generated by running the script `doxytest.py` to extract tests from comments in input files.
// Input file(s): `BitSpan.h`
// Do not edit this file manually -- it may be overwritten.
// Generated on: 2026-01-26 16:50:00

#include "../include/gf2/BitSpan.h"
#include <cstdlib>
#include <exception>
#include <format>
#include <print>
#include <source_location>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <utility>
#include <vector>
#include <gf2/namespace.h>

// We use our own assert macros instead of the standard ones.
#ifdef assert
    #undef assert
#endif
#ifdef assert_eq
    #undef assert_eq
#endif

#define assert(cond, ...) \
    if(!(cond)) doxy::failed(#cond, header_file, header_line __VA_OPT__(, __VA_ARGS__));

#define assert_eq(a, b, ...) \
    if(!((a) == (b))) doxy::failed_eq(#a, #b, (a), (b), header_file, header_line __VA_OPT__(, __VA_ARGS__));

namespace doxy {

// Maximum number of allowed failures before we exit the program.
std::size_t max_fails = 10;

// A simple exception class for test failures.
struct error : public std::exception {
    explicit error(std::string message) : m_message(std::move(message)) {}
    const char* what() const noexcept override { return m_message.c_str(); }
    std::string m_message;
};

// Program exit (possibly break in `doxy::exit` if you are debugging a test failure).
void exit(int status) { ::exit(status); }

// Handle boolean condition assertion evaluation failures.
template <typename... Args>
void
failed(std::string_view cond_str, std::string_view hdr_file, std::size_t hdr_line, 
       std::string_view msg_format = "", Args&&... msg_args) {
    auto what = std::format("\nFAILED `assert({})` [{}:{}]\n", cond_str, hdr_file, hdr_line);
    if (!msg_format.empty()) {
        auto arg_storage = std::tuple<std::decay_t<Args>...>(std::forward<Args>(msg_args)...);
        auto format_args = std::apply([](auto&... values) { return std::make_format_args<std::format_context>(values...); }, arg_storage);
        what += std::vformat(msg_format, format_args);
        what.push_back('\n');
    }
    throw error{std::move(what)};
}

// Handle equality assertion evaluation failures.
template <typename LHS, typename RHS, typename... Args>
void
failed_eq(std::string_view lhs_str, std::string_view rhs_str, const LHS& lhs, const RHS& rhs,
          std::string_view hdr_file, std::size_t hdr_line, std::string_view msg_format = "", Args&&... msg_args) {
    auto what = std::format("\nFAILED `assert_eq({}, {})` [{}:{}]\n", lhs_str, rhs_str, hdr_file, hdr_line);
    if (!msg_format.empty()) {
        auto arg_storage = std::tuple<std::decay_t<Args>...>(std::forward<Args>(msg_args)...);
        auto format_args = std::apply([](auto&... values) { return std::make_format_args<std::format_context>(values...); }, arg_storage);
        what += std::vformat(msg_format, format_args);
        what.push_back('\n');
    }
    what += std::format("lhs = {}\n", lhs);
    what += std::format("rhs = {}\n", rhs);
    throw error{std::move(what)};
}

} // namespace doxy

int
main() {
    // Trace the source for the tests.
    auto header_file = "BitSpan.h";
    std::size_t test_count = 53;
    std::println(stderr, "Running {} tests extracted from: `{}`", test_count, header_file);

    // Number of failed doctests (we exit the program if this exceeds doxy::max_fails).
    std::size_t fails = 0;

    // Variables used to track the current test.
    std::size_t header_line = 0;
    std::size_t test = 0;
    auto test_passed = true;

    // Cache of all failed test messages.
    std::vector<std::string> failed_messages;

    // Each test failure is handled the same way:
    auto handle_failure = [&](std::string_view message) {
        test_passed = false;
        fails++;
        std::println(stderr, "FAIL");
        std::println(stderr, "{}", message);
        failed_messages.push_back(std::string(message));
        if (fails >= doxy::max_fails) {
            std::println(stderr);
            std::println(stderr, "Hit the maximum allowed number of failures ({}) for `{}`:", doxy::max_fails, header_file);
            std::println(stderr, "Managed to run {} of a possible {} tests, PASSED: {}, FAILED: {}", test, test_count, test - fails, fails);
            std::println(stderr, "Here is a summary of the failed tests:");
            for (const auto& msg : failed_messages) std::print(stderr, "{}", msg);
            doxy::exit(1);
        };
    };
    // Run the tests ...
    header_line = 70;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        std::vector<u8> words{0b1010'1010, 0b1100'1100};
        BitSpan s{words.data(), 0, 16};
        assert_eq(s.to_string(), "0101010100110011");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 95;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        std::vector<u8> words{0b1010'1010, 0b1100'1100};
        BitSpan s{words.data(), 0, 16};
        assert_eq(s.size(), 16);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 110;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(18);
        assert_eq(v.words(), 3);
        auto s = v.span(4, 12);     // The span covers words 0 and 1 in the span underlying v.
        assert_eq(s.words(), 1);    // However, it can be fitted into a single synthetic word!
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 127;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::from_string("0000'0000'1111'1111").value();
        auto s = v.span(4, 12);     // The span covers words 0 and 1 in the span underlying v.
        assert_eq(s.words(), 1);    // However, it can be fitted into a single synthetic word!
        assert_eq(s.word(0), 0b1111'0000);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 162;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::from_string("0000_0000_1111_1111").value();
        auto s = v.span(4, 12);     // The span covers words 0 and 1 in the span underlying v.
        assert_eq(s.words(), 1);    // However, it can be fitted into a single synthetic word!
        assert_eq(s.word(0), 0b1111'0000);
        s.set_word(0, 0b1111'1111);
        assert_eq(v.to_string(), "0000111111111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 209;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVector u{10};
        auto v = u.span(0,2);
        assert_eq(v.get(0), false);
        u.set(0);
        assert_eq(v.get(0), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 224;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVector u{10};
        auto v = u.span(1, 4);
        assert_eq(v[0], false);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 237;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::ones(10);
        auto v = u.span(0,3);
        assert_eq(v.front(), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 250;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::ones(10);
        auto v = u.span(0,3);
        assert_eq(v.back(), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 268;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::zeros(10);
        auto v = u.span(0,3);
        assert_eq(v.get(0), false);
        v.set(0);
        assert_eq(v.get(0), true);
        assert_eq(u.get(0), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 291;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::zeros(10);
        auto v = u.span(0,5);
        v[2] = true;
        assert_eq(v.to_string(), "00100");
        assert_eq(u.to_string(), "0010000000");
        auto w = BitVector<>::ones(10);
        v[3] = w[3];
        assert_eq(v.to_string(), "00110");
        v[4] |= w[4];
        assert_eq(v.to_string(), "00111");
        assert_eq(u.to_string(), "0011100000")
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 312;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::ones(10);
        auto v = u.span(1,5);
        assert_eq(v.to_string(), "1111");
        v.flip(0);
        assert_eq(v.to_string(), "0111");
        assert_eq(u.to_string(), "1011111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 331;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::zeros(10);
        auto v = u.span(1,5);
        v.set(0);
        assert_eq(v.to_string(), "1000");
        assert_eq(u.to_string(), "0100000000");
        v.swap(0, 1);
        assert_eq(v.to_string(), "0100");
        assert_eq(u.to_string(), "0010000000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 353;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::zeros(10);
        auto v = u.span(1,1);
        assert_eq(v.is_empty(), true);
        auto w = u.span(0,1);
        assert_eq(w.is_empty(), false);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 367;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::zeros(10);
        auto v = u.span(1,3);
        assert_eq(v.any(), false);
        v.set(0);
        assert_eq(v.any(), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 381;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::zeros(10);
        auto v = u.span(1,3);
        assert_eq(v.all(), false);
        v.set(0);
        v.set(1);
        assert_eq(v.all(), true);
        assert_eq(u.all(), false);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 397;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::zeros(10);
        auto v = u.span(1,3);
        assert_eq(v.none(), true);
        v.set(0);
        assert_eq(v.none(), false);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 415;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::zeros(10);
        auto v = u.span(5,10);
        v.set_all();
        assert_eq(v.to_string(), "11111");
        assert_eq(u.to_string(), "0000011111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 427;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::zeros(10);
        auto v = u.span(5,10);
        v.flip_all();
        assert_eq(v.to_string(), "11111");
        assert_eq(u.to_string(), "0000011111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 451;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVector<u8> v{26};
        auto s = v.span(3, 19);
        u16 src = 0b1010101010101010;
        s.copy(src);
        assert_eq(s.to_string(), "0101010101010101");
        assert_eq(v.to_string(), "00001010101010101010000000");
        BitVector<u32> w{26};
        auto t = w.span(3, 19);
        t.copy(src);
        assert_eq(t.to_string(), "0101010101010101");
        assert_eq(w.to_string(), "00001010101010101010000000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 481;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(16);
        assert_eq(v.to_string(), "1111111111111111");
        auto s = v.span(0,10);
        s.copy(BitVector<u8>::alternating(10));
        assert_eq(v.to_string(), "1010101010111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 504;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        std::bitset<10> src{0b1010101010};
        auto v = BitVector<u8>::ones(16);
        auto s = v.span(0,10);
        s.copy(src);
        assert_eq(s.to_string(), "0101010101");
        assert_eq(v.to_string(), "0101010101111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 526;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(16);
        auto s = v.span(0,10);
        s.copy([](usize i) { return i % 2 == 0; });
        assert_eq(s.to_string(), "1010101010");
        assert_eq(v.to_string(), "1010101010111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 548;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVector u{10}, v{10};
        auto s = u.span(2,10);
        auto t = v.span(2,10);
        u64 seed = 1234567890;
        s.fill_random(0.5, seed);
        t.fill_random(0.5, seed);
        assert(u == v);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 569;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVector v{10};
        auto s = v.span(2,10);
        assert_eq(s.count_ones(), 0);
        v.set(2);
        assert_eq(s.count_ones(), 1);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 581;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVector v{10};
        auto s = v.span(2,10);
        assert_eq(s.count_zeros(), 8);
        v.set(2);
        assert_eq(s.count_zeros(), 7);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 593;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVector v{37};
        auto s = v.span(2,10);
        assert_eq(s.leading_zeros(), 8);
        v.set(11);
        assert_eq(s.leading_zeros(), 8);
        v.set(2);
        assert_eq(s.leading_zeros(), 0);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 607;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::zeros(27);
        auto s = v.span(2,10);
        assert_eq(s.trailing_zeros(), 8);
        v.set(11);
        assert_eq(s.trailing_zeros(), 8);
        v.set(2);
        assert_eq(s.trailing_zeros(), 7);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 625;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::zeros(37);
        auto s = v.span(4,12);
        assert(s.first_set() == std::optional<usize>{});
        v.set(2);
        assert(s.first_set() == std::optional<usize>{});
        v.set(4);
        assert(s.first_set() == std::optional<usize>{0});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 639;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::zeros(37);
        auto s = v.span(4,12);
        assert(s.last_set() == std::optional<usize>{});
        v.set(27);
        assert(s.last_set() == std::optional<usize>{});
        v.set(11);
        assert_eq(s.to_string(), "00000001");
        assert(s.last_set() == std::optional<usize>{7});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 654;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::zeros(37);
        auto s = v.span(4,12);
        assert(s.next_set(0) == std::optional<usize>{});
        v.set(5);
        v.set(6);
        assert(s.next_set(0) == std::optional<usize>{1});
        assert(s.next_set(1) == std::optional<usize>{2});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 668;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::zeros(37);
        auto s = v.span(4,12);
        assert(s.previous_set(s.size()) == std::optional<usize>{});
        v.set(5);
        v.set(6);
        assert(s.previous_set(s.size()) == std::optional<usize>{2});
        assert(s.previous_set(2) == std::optional<usize>{1});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 686;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(37);
        auto s = v.span(4,12);
        assert(s.first_unset() == std::optional<usize>{});
        v.set(2, false);
        assert(s.first_unset() == std::optional<usize>{});
        v.set(4, false);
        assert(s.first_unset() == std::optional<usize>{0});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 700;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(37);
        auto s = v.span(4,12);
        assert(s.last_unset() == std::optional<usize>{});
        v.set(27);
        assert(s.last_unset() == std::optional<usize>{});
        v.set(4, false);
        assert_eq(s.to_string(), "01111111");
        assert(s.last_unset() == std::optional<usize>{0});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 715;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(37);
        auto s = v.span(4,12);
        assert(s.last_unset() == std::optional<usize>{});
        v.set(27);
        assert(s.last_unset() == std::optional<usize>{});
        v.set(11, false);
        assert_eq(s.to_string(), "11111110");
        assert(s.last_unset() == std::optional<usize>{7});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 730;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(37);
        auto s = v.span(4,12);
        assert(s.previous_unset(s.size()) == std::optional<usize>{});
        v.set(5, false);
        v.set(6, false);
        assert(s.previous_unset(s.size()) == std::optional<usize>{2});
        assert(s.previous_unset(2) == std::optional<usize>{1});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 754;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<u8>::ones(14);
        auto s = u.span(4,12);
        for (auto&& bit : s.bits()) assert_eq(bit, true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 770;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<u8>::ones(14);
        auto s = u.span(4,12);
        for (auto&& bit : s.bits()) bit = false;
        assert_eq(s.to_string(), "00000000")
        assert_eq(u.to_string(), "11110000000011");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 784;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::alternating(19);
        auto s = v.span(4,12);
        assert_eq(s.to_string(), "10101010");
        auto indices = std::ranges::to<std::vector>(s.set_bits());
        assert_eq(indices, (std::vector<usize>{0, 2, 4, 6}));
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 798;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::alternating(19);
        auto s = v.span(4,12);
        assert_eq(s.to_string(), "10101010");
        auto indices = std::ranges::to<std::vector>(s.unset_bits());
        assert_eq(indices, (std::vector<usize>{1, 3, 5, 7}));
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 819;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(100);
        auto s = v.span(4,14);
        assert_eq(s.to_string(), "1111111111");
        auto words = std::ranges::to<std::vector>(s.store_words());
        assert_eq(words, (std::vector<u8>{0b1111'1111, 0b0000'0011}));
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 833;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(100);
        auto s = v.span(4,14);
        assert_eq(s.to_string(), "1111111111");
        auto words = s.to_words();
        assert_eq(words, (std::vector<u8>{0b1111'1111, 0b0000'0011}));
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 854;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        const auto v = BitVector<u8>::alternating(14);
        const auto s0 = v.span(4,12);
        assert_eq(s0.to_string(), "10101010");
        auto s1 = s0.span(4,8);
        assert_eq(s1.to_string(), "1010")
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 871;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::alternating(14);
        auto s0 = v.span(4,12);
        assert_eq(s0.to_string(), "10101010");
        auto s1 = s0.span(4,8);
        assert_eq(s1.to_string(), "1010")
        s1.set_all();
        assert_eq(s1.to_string(), "1111")
        assert_eq(s0.to_string(), "10101111");
        assert_eq(v.to_string(), "10101010111110");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 894;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::alternating(14);
        auto s = u.span(4,12);
        auto v = s.sub(0,4);
        assert_eq(v.to_string(), "1010");
        s.set_all();
        assert_eq(s.to_string(), "11111111");
        assert_eq(u.to_string(), "10101111111110");
        assert_eq(v.to_string(), "1010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 924;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::alternating(14);
        auto s = u.span(4,12);
        BitVector left, right;
        s.split_at(5, left, right);
        assert_eq(left.to_string(), "10101");
        assert_eq(right.to_string(), "010");
        assert_eq(u.to_string(), "10101010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 948;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVector<>::alternating(14);
        auto s = u.span(4,12);
        auto [left, right] = s.split_at(5);
        assert_eq(left.to_string(), "10101");
        assert_eq(right.to_string(), "010");
        assert_eq(u.to_string(), "10101010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 970;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(20);
        BitVector<u8> dst;
        v.span(4,14).riffled(dst);
        assert_eq(dst.to_string(), "1010101010101010101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 985;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(20);
        auto dst = v.span(4,14).riffled();
        assert_eq(dst.to_string(), "1010101010101010101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 1005;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVector v{14};
        auto s = v.span(2,12);
        assert_eq(s.to_binary_string(), "0000000000");
        s.set(0);
        assert_eq(s.to_binary_string(), "1000000000");
        assert_eq(v.to_binary_string(",", "[", "]"), "[0,0,1,0,0,0,0,0,0,0,0,0,0,0]");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 1027;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVector v{14};
        auto s = v.span(2,12);
        assert_eq(s.to_binary_string(), "0000000000");
        s.set(0);
        assert_eq(s.to_binary_string(), "1000000000");
        assert_eq(v.to_binary_string(",", "[", "]"), "[0,0,1,0,0,0,0,0,0,0,0,0,0,0]");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 1045;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::alternating(14);
        auto s = v.span(2,12);
        assert_eq(s.to_pretty_string(), "[1,0,1,0,1,0,1,0,1,0]");
        auto empty = v.span(3,3);
        assert_eq(empty.to_pretty_string(), "[]");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 1073;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVector<u8>::ones(20);
        assert_eq(v.span(4,4).to_hex_string(), "");
        assert_eq(v.span(4,8).to_hex_string(), "F");
        assert_eq(v.span(4,9).to_hex_string(), "F1.2");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    // Print a summary of the tests results.
    if (fails == 0) {
        std::println(stderr, "[{}] All {} tests PASSED", header_file, test_count);
    } else {
        std::println(stderr);
        std::println(stderr, "Test FAIL summary for `{}`: Ran {} of a possible {} tests, PASSED: {}, FAILED: {}", header_file, test, test_count, test - fails, fails);
        std::print(stderr, "--------------------------------------------------------------------------------------");
        for (const auto& msg : failed_messages) std::print(stderr, "{}", msg);
    }

    // Return 1 if there were any failures, 0 otherwise.
    return fails > 0 ? 1 : 0;
}