// This file was generated by running the script `doxytest.py` to extract tests from comments in input files.
// Input file(s): `BitVec.h`
// Do not edit this file manually -- it may be overwritten.
// Generated on: 2025-11-30 15:49:37

#include "../include/gf2/BitVec.h"
#include <cstdlib>
#include <exception>
#include <format>
#include <print>
#include <source_location>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <utility>
#include <vector>
#include <gf2/namespace.h>

// We use our own assert macros instead of the standard ones.
#ifdef assert
    #undef assert
#endif
#ifdef assert_eq
    #undef assert_eq
#endif

#define assert(cond, ...) \
    if(!(cond)) doxy::failed(#cond, header_file, header_line __VA_OPT__(, __VA_ARGS__));

#define assert_eq(a, b, ...) \
    if(!((a) == (b))) doxy::failed_eq(#a, #b, (a), (b), header_file, header_line __VA_OPT__(, __VA_ARGS__));

namespace doxy {

// Maximum number of allowed failures before we exit the program.
std::size_t max_fails = 10;

// A simple exception class for test failures.
struct error : public std::exception {
    explicit error(std::string message) : m_message(std::move(message)) {}
    const char* what() const noexcept override { return m_message.c_str(); }
    std::string m_message;
};

// Program exit (possibly break in `doxy::exit` if you are debugging a test failure).
void exit(int status) { ::exit(status); }

// Handle boolean condition assertion evaluation failures.
template <typename... Args>
void
failed(std::string_view cond_str, std::string_view hdr_file, std::size_t hdr_line, 
       std::string_view msg_format = "", Args&&... msg_args) {
    auto what = std::format("\nFAILED `assert({})` [{}:{}]\n", cond_str, hdr_file, hdr_line);
    if (!msg_format.empty()) {
        auto arg_storage = std::tuple<std::decay_t<Args>...>(std::forward<Args>(msg_args)...);
        auto format_args = std::apply([](auto&... values) { return std::make_format_args<std::format_context>(values...); }, arg_storage);
        what += std::vformat(msg_format, format_args);
        what.push_back('\n');
    }
    throw error{std::move(what)};
}

// Handle equality assertion evaluation failures.
template <typename LHS, typename RHS, typename... Args>
void
failed_eq(std::string_view lhs_str, std::string_view rhs_str, const LHS& lhs, const RHS& rhs,
          std::string_view hdr_file, std::size_t hdr_line, std::string_view msg_format = "", Args&&... msg_args) {
    auto what = std::format("\nFAILED `assert_eq({}, {})` [{}:{}]\n", lhs_str, rhs_str, hdr_file, hdr_line);
    if (!msg_format.empty()) {
        auto arg_storage = std::tuple<std::decay_t<Args>...>(std::forward<Args>(msg_args)...);
        auto format_args = std::apply([](auto&... values) { return std::make_format_args<std::format_context>(values...); }, arg_storage);
        what += std::vformat(msg_format, format_args);
        what.push_back('\n');
    }
    what += std::format("lhs = {}\n", lhs);
    what += std::format("rhs = {}\n", rhs);
    throw error{std::move(what)};
}

} // namespace doxy

int
main() {
    // Trace the source for the tests.
    auto header_file = "BitVec.h";
    std::size_t test_count = 36;
    std::println(stderr, "Running {} tests extracted from: `{}`", test_count, header_file);

    // Number of failed doctests (we exit the program if this exceeds doxy::max_fails).
    std::size_t fails = 0;

    // Variables used to track the current test.
    std::size_t header_line = 0;
    std::size_t test = 0;
    auto test_passed = true;

    // Cache of all failed test messages.
    std::vector<std::string> failed_messages;

    // Each test failure is handled the same way:
    auto handle_failure = [&](std::string_view message) {
        test_passed = false;
        fails++;
        std::println(stderr, "FAIL");
        std::println(stderr, "{}", message);
        failed_messages.push_back(std::string(message));
        if (fails >= doxy::max_fails) {
            std::println(stderr);
            std::println(stderr, "Hit the maximum allowed number of failures ({}) for `{}`:", doxy::max_fails, header_file);
            std::println(stderr, "Managed to run {} of a possible {} tests, PASSED: {}, FAILED: {}", test, test_count, test - fails, fails);
            std::println(stderr, "Here is a summary of the failed tests:");
            for (const auto& msg : failed_messages) std::print(stderr, "{}", msg);
            doxy::exit(1);
        };
    };
    // Run the tests ...
    header_line = 58;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVec v0;
        assert_eq(v0.size(), 0);
        BitVec<u8> v1(10);
        assert_eq(v1.size(), 10);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 71;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVec v0;
        assert_eq(v0.words(), 0);
        BitVec<u8> v1(10);
        assert_eq(v1.words(), 2);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 86;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::ones(10);
        assert_eq(v.to_string(), "1111111111");
        assert_eq(v.words(), 2);
        assert_eq(v.word(0), 0b1111'1111);
        assert_eq(v.word(1), 0b0000'0011);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 105;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::zeros(10);
        assert_eq(v.to_string(), "0000000000");
        v.set_word(1, 0b1111'1111);
        assert_eq(v.to_string(), "0000000011");
        assert_eq(v.count_ones(), 2);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 123;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::ones(10);
        auto ptr = v.data();
        assert_eq(*ptr, 0b1111'1111);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 135;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::ones(10);
        auto ptr = v.data();
        assert_eq(*ptr, 0b1111'1111);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 160;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVec v0;
        assert_eq(v0.to_string(), "");
        BitVec<u8> v1{10};
        assert_eq(v1.to_string(), "0000000000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 177;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVec<u8> v{10, u8{0b0101'0101}};
        assert_eq(v.size(), 10);
        assert_eq(v.to_string(), "1010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 194;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<>::with_capacity(10);
        assert_eq(v.size(), 0);
        assert(v.capacity() >=10);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 208;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<>::zeros(10);
        assert_eq(v.to_string(), "0000000000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 217;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        assert_eq(BitVec<>::ones(10).to_string(), "1111111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 225;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<>::constant(10, true);
        assert_eq(v.to_string(), "1111111111");
        auto w = BitVec<>::constant(10, false);
        assert_eq(w.to_string(), "0000000000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 238;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        assert_eq(BitVec<>::unit(10, 0).to_string(), "1000000000");
        assert_eq(BitVec<>::unit(10, 9).to_string(), "0000000001");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 252;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        assert_eq(BitVec<u8>::alternating(10).to_string(), "1010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 265;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::from(BitVec<u8>::ones(10));
        assert_eq(v.size(), 10);
        assert_eq(v.to_string(), "1111111111");
        auto w = BitVec<u8>::from(BitVec<u16>::ones(20));
        assert_eq(w.size(), 20);
        assert_eq(w.to_string(), "11111111111111111111");
        auto x = BitVec<u8>::from(BitVec<u32>::zeros(10));
        assert_eq(x.size(), 10);
        assert_eq(x.to_string(), "0000000000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 288;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        std::bitset<10> src{0b1010101010};
        auto v = BitVec<>::from(src);
        assert_eq(v.to_string(), "0101010101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 306;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::from(10, [](usize i) { return i % 2 == 0; });
        assert_eq(v.size(), 10);
        assert_eq(v.to_string(), "1010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 333;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        u64 seed = 1234567890;
        auto u = BitVec<>::random(10, 0.5, seed);
        auto v = BitVec<>::random(10, 0.5, seed);
        assert(u == v);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 356;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        u64 seed = 1234567890;
        auto u = BitVec<>::seeded_random(10, seed);
        auto v = BitVec<>::seeded_random(10, seed);
        assert(u == v);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 371;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto u = BitVec<>::biased_random(10, 0.3);
        auto v = BitVec<>::biased_random(10, 0.3);
        assert_eq(u.size(), v.size());
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 392;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v1 = BitVec<>::from_string("0b1010_1010_10").value();
        assert_eq(v1.to_string(), "1010101010");
        auto v2 = BitVec<>::from_string("AA").value();
        assert_eq(v2.to_string(), "10101010");
        auto v3 = BitVec<>::from_string("1010'1010").value();
        assert_eq(v3.to_string(), "10101010");
        auto v4 = BitVec<>::from_string("0x1.8").value();
        assert_eq(v4.to_string(), "001");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 433;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::from_binary_string("0b1010'1010'10");
        assert_eq(v->to_string(), "1010101010");
        auto u = BitVec<u8>::from_binary_string("");
        assert_eq(u->to_string(), "");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 468;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v1 = gf2::BitVec<>::from_hex_string("0xAA").value();
        assert_eq(v1.to_string(), "10101010");
        auto v2 = gf2::BitVec<>::from_hex_string("0x1").value();
        assert_eq(v2.to_string(), "0001");
        auto v3 = gf2::BitVec<>::from_hex_string("0x1.8").value();
        assert_eq(v3.to_string(), "001");
        auto v4 = gf2::BitVec<>::from_hex_string("0x1.4").value();
        assert_eq(v4.to_string(), "01");
        auto v5 = gf2::BitVec<>::from_hex_string("0x1.2").value();
        assert_eq(v5.to_string(), "1");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 529;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVec v0;
        assert_eq(v0.capacity(), 0);
        BitVec<u64> v1(10);
        assert_eq(v1.capacity(), 64);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 542;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::ones(1000);
        v.resize(15);
        v.shrink_to_fit();
        assert_eq(v.capacity(), 16);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 569;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::ones(1000);
        v.resize(10);
        assert_eq(v.to_string(), "1111111111");
        v.resize(15);
        assert_eq(v.to_string(), "111111111100000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 606;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVec v;
        v.push(1);
        assert(v.to_string() == "1");
        v.push(0);
        assert(v.to_string() == "10");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 624;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::ones(4);
        u16 src = 0b1010101010101010;
        v.append(src);
        assert_eq(v.to_string(), "11110101010101010101");
        auto w = BitVec<u32>::ones(4);
        w.append(src);
        assert_eq(w.to_string(), "11110101010101010101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 648;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::zeros(10);
        auto w = BitVec<u16>::ones(10);
        v.append(w);
        assert_eq(v.size(), 20);
        assert_eq(v.to_string(), "00000000001111111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 666;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        std::bitset<10> src{0b1010101010};
        BitVec v;
        v.append(src);
        assert_eq(v.to_string(), "0101010101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 687;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVec v;
        v.append_digit('A', 16);
        assert_eq(v.to_string(), "1010");
        v.append_digit('X', 16);
        assert_eq(v.to_string(), "1010");
        v.append_digit('1', 8);
        assert_eq(v.to_string(), "1010001");
        v.append_digit('1', 4);
        assert_eq(v.to_string(), "101000101");
        v.append_digit('1', 2);
        assert_eq(v.to_string(), "1010001011");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 725;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVec v;
        v.append_hex_digit('F');
        assert_eq(v.to_string(), "1111");
        v.append_hex_digit('X');
        assert_eq(v.to_string(), "1111");
        v.append_hex_digit('1');
        assert_eq(v.to_string(), "11110001");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 753;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitVec v;
        v.push(1);
        v.push(0);
        assert(v.to_string() == "10");
        auto b1 = v.pop();
        assert_eq(*b1, false);
        assert(v.to_string() == "1");
        auto b2 = v.pop();
        assert_eq(*b2, true);
        assert(v.to_string() == "");
        auto b3 = v.pop();
        assert(b3 == std::nullopt);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 782;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<>::alternating(10);
        BitVec dst;
        v.split_off(5, dst);
        assert_eq(v.to_string(), "10101");
        assert_eq(dst.to_string(), "01010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 804;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<>::alternating(10);
        auto w = v.split_off(5);
        assert_eq(v.to_string(), "10101");
        assert_eq(w.to_string(), "01010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 825;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        auto v = BitVec<u8>::ones(22);
        auto x16 = v.split_off_unsigned<u16>();
        assert_eq(*x16, 0b1111'1111'1111'1111);
        assert_eq(v.size(), 6);
        assert_eq(v.to_string(), "111111");
        auto w = BitVec<u8>::alternating(24);
        auto x8 = w.split_off_unsigned<u8>();
        assert_eq(*x8, 0b0101'0101);
        assert_eq(w.size(), 16);
        assert_eq(w.to_string(), "1010101010101010");
        w.append(*x8);
        assert_eq(w.to_string(), "101010101010101010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    // Print a summary of the tests results.
    if (fails == 0) {
        std::println(stderr, "[{}] All {} tests PASSED", header_file, test_count);
    } else {
        std::println(stderr);
        std::println(stderr, "Test FAIL summary for `{}`: Ran {} of a possible {} tests, PASSED: {}, FAILED: {}", header_file, test, test_count, test - fails, fails);
        std::print(stderr, "--------------------------------------------------------------------------------------");
        for (const auto& msg : failed_messages) std::print(stderr, "{}", msg);
    }

    // Return 1 if there were any failures, 0 otherwise.
    return fails > 0 ? 1 : 0;
}