// This file was generated by running the script `doxytest.py` to extract tests from comments in input files.
// Input file(s): `BitSet.h`
// Do not edit this file manually -- it may be overwritten.
// Generated on: 2025-12-29 16:51:15

#include "../include/gf2/BitSet.h"
#include <cstdlib>
#include <exception>
#include <format>
#include <print>
#include <source_location>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <utility>
#include <vector>
#include <gf2/namespace.h>

// We use our own assert macros instead of the standard ones.
#ifdef assert
    #undef assert
#endif
#ifdef assert_eq
    #undef assert_eq
#endif

#define assert(cond, ...) \
    if(!(cond)) doxy::failed(#cond, header_file, header_line __VA_OPT__(, __VA_ARGS__));

#define assert_eq(a, b, ...) \
    if(!((a) == (b))) doxy::failed_eq(#a, #b, (a), (b), header_file, header_line __VA_OPT__(, __VA_ARGS__));

namespace doxy {

// Maximum number of allowed failures before we exit the program.
std::size_t max_fails = 10;

// A simple exception class for test failures.
struct error : public std::exception {
    explicit error(std::string message) : m_message(std::move(message)) {}
    const char* what() const noexcept override { return m_message.c_str(); }
    std::string m_message;
};

// Program exit (possibly break in `doxy::exit` if you are debugging a test failure).
void exit(int status) { ::exit(status); }

// Handle boolean condition assertion evaluation failures.
template <typename... Args>
void
failed(std::string_view cond_str, std::string_view hdr_file, std::size_t hdr_line, 
       std::string_view msg_format = "", Args&&... msg_args) {
    auto what = std::format("\nFAILED `assert({})` [{}:{}]\n", cond_str, hdr_file, hdr_line);
    if (!msg_format.empty()) {
        auto arg_storage = std::tuple<std::decay_t<Args>...>(std::forward<Args>(msg_args)...);
        auto format_args = std::apply([](auto&... values) { return std::make_format_args<std::format_context>(values...); }, arg_storage);
        what += std::vformat(msg_format, format_args);
        what.push_back('\n');
    }
    throw error{std::move(what)};
}

// Handle equality assertion evaluation failures.
template <typename LHS, typename RHS, typename... Args>
void
failed_eq(std::string_view lhs_str, std::string_view rhs_str, const LHS& lhs, const RHS& rhs,
          std::string_view hdr_file, std::size_t hdr_line, std::string_view msg_format = "", Args&&... msg_args) {
    auto what = std::format("\nFAILED `assert_eq({}, {})` [{}:{}]\n", lhs_str, rhs_str, hdr_file, hdr_line);
    if (!msg_format.empty()) {
        auto arg_storage = std::tuple<std::decay_t<Args>...>(std::forward<Args>(msg_args)...);
        auto format_args = std::apply([](auto&... values) { return std::make_format_args<std::format_context>(values...); }, arg_storage);
        what += std::vformat(msg_format, format_args);
        what.push_back('\n');
    }
    what += std::format("lhs = {}\n", lhs);
    what += std::format("rhs = {}\n", rhs);
    throw error{std::move(what)};
}

} // namespace doxy

int
main() {
    // Trace the source for the tests.
    auto header_file = "BitSet.h";
    std::size_t test_count = 54;
    std::println(stderr, "Running {} tests extracted from: `{}`", test_count, header_file);

    // Number of failed doctests (we exit the program if this exceeds doxy::max_fails).
    std::size_t fails = 0;

    // Variables used to track the current test.
    std::size_t header_line = 0;
    std::size_t test = 0;
    auto test_passed = true;

    // Cache of all failed test messages.
    std::vector<std::string> failed_messages;

    // Each test failure is handled the same way:
    auto handle_failure = [&](std::string_view message) {
        test_passed = false;
        fails++;
        std::println(stderr, "FAIL");
        std::println(stderr, "{}", message);
        failed_messages.push_back(std::string(message));
        if (fails >= doxy::max_fails) {
            std::println(stderr);
            std::println(stderr, "Hit the maximum allowed number of failures ({}) for `{}`:", doxy::max_fails, header_file);
            std::println(stderr, "Managed to run {} of a possible {} tests, PASSED: {}, FAILED: {}", test, test_count, test - fails, fails);
            std::println(stderr, "Here is a summary of the failed tests:");
            for (const auto& msg : failed_messages) std::print(stderr, "{}", msg);
            doxy::exit(1);
        };
    };
    // Run the tests ...
    header_line = 42;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v.size(), 10);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 53;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v0;
        assert_eq(v0.words(), 2);
        BitSet<10, u16> v1;
        assert_eq(v1.words(), 1);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 68;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        assert_eq(v.to_string(), "0000000000");
        v.set_all();
        assert_eq(v.to_string(), "1111111111");
        assert_eq(v.words(), 2);
        assert_eq(v.word(0), 0b1111'1111);
        assert_eq(v.word(1), 0b0000'0011);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 89;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        assert_eq(v.to_string(), "0000000000");
        v.set_word(1, 0b1111'1111);
        assert_eq(v.to_string(), "0000000011");
        assert_eq(v.count_ones(), 2);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 107;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        v.set_all();
        auto ptr = v.data();
        assert_eq(*ptr, 0b1111'1111);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 120;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        v.set_all();
        auto ptr = v.data();
        assert_eq(*ptr, 0b1111'1111);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 155;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v.get(0), false);
        v.set(0);
        assert_eq(v.get(0), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 168;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert(v[2] == false);
        v[2] = true;
        assert(v[2] == true);
        assert(v.to_string() == "0010000000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 182;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v.front(), false);
        v.set_all();
        assert_eq(v.front(), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 195;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v.back(), false);
        v.set_all();
        assert_eq(v.back(), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 213;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v[0], false);
        v.set(0);
        assert_eq(v[0], true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 229;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        v[2] = true;
        assert(v.to_string() == "0010000000");
        BitSet<10> w;
        w.set_all();
        v[3] = w[3];
        assert(v.to_string() == "0011000000");
        v[4] |= w[4];
        assert(v.to_string() == "0011100000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 247;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10,u8> v;
        v.set_all();
        v.flip(0);
        assert_eq(v.to_string(), "0111111111");
        v.flip(1);
        assert_eq(v.to_string(), "0011111111");
        v.flip(9);
        assert_eq(v.to_string(), "0011111110");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 264;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        v.set(0);
        assert_eq(v.to_string(), "1000000000");
        v.swap(0, 1);
        assert_eq(v.to_string(), "0100000000");
        v.swap(0, 1);
        assert_eq(v.to_string(), "1000000000");
        v.swap(0, 9);
        assert_eq(v.to_string(), "0000000001");
        v.swap(0, 9);
        assert_eq(v.to_string(), "1000000000");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 286;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<0> v;
        assert_eq(v.is_empty(), true);
        BitSet<10> u;
        assert_eq(u.is_empty(), false);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 299;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v.any(), false);
        v.set(0);
        assert_eq(v.any(), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 312;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<3> v;
        assert_eq(v.all(), false);
        v.set(0);
        v.set(1);
        v.set(2);
        assert_eq(v.all(), true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 327;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v.none(), true);
        v.set(0);
        assert_eq(v.none(), false);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 344;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        v.set_all();
        assert_eq(v.to_string(), "1111111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 354;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        v.flip_all();
        assert_eq(v.to_string(), "1111111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 373;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<16, u8> v;
        u16 src = 0b1010101010101010;
        v.copy_from(src);
        assert_eq(v.to_string(), "0101010101010101");
        BitSet<16, u32> w;
        w.copy_from(src);
        assert_eq(w.to_string(), "0101010101010101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 394;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u64> v;
        assert_eq(v.to_string(), "0000000000");
        v.copy_from(BitVec<u8>::alternating(10));
        assert_eq(v.to_string(), "1010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 410;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        std::bitset<10> src{0b1010101010};
        BitSet<10> v;
        v.copy_from(src);
        assert_eq(v.to_string(), "0101010101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 425;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        v.fill_from([](usize i) { return i % 2 == 0; });
        assert_eq(v.size(), 10);
        assert_eq(v.to_string(), "1010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 443;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> u, v;
        u64 seed = 1234567890;
        u.fill_from_random(0.5, seed);
        v.fill_from_random(0.5, seed);
        assert(u == v);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 459;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v.count_ones(), 0);
        v.set(0);
        assert_eq(v.count_ones(), 1);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 470;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v.count_zeros(), 10);
        v.set(0);
        assert_eq(v.count_zeros(), 9);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 481;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v;
        assert_eq(v.leading_zeros(), 37);
        v.set(27);
        assert_eq(v.leading_zeros(), 27);
        BitSet<10, u8> w;
        w.set_all();
        assert_eq(w.leading_zeros(), 0);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 495;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<27, u8> v;
        assert_eq(v.trailing_zeros(), 27);
        v.set(0);
        assert_eq(v.trailing_zeros(), 26);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 510;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v;
        assert(v.first_set() == std::optional<usize>{});
        v.set(2);
        assert(v.first_set() == std::optional<usize>{2});
        v.set(2, false);
        assert(v.first_set() == std::optional<usize>{});
        v.set(27);
        assert(v.first_set() == std::optional<usize>{27});
        BitSet<0> empty;
        assert(empty.first_set() == std::optional<usize>{});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 527;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v;
        assert(v.last_set() == std::optional<usize>{});
        v.set(2);
        assert(v.last_set() == std::optional<usize>{2});
        v.set(27);
        assert(v.last_set() == std::optional<usize>{27});
        BitSet<0> empty;
        assert(empty.last_set() == std::optional<usize>{});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 542;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v;
        assert(v.next_set(0) == std::optional<usize>{});
        v.set(2);
        v.set(27);
        assert(v.next_set(0) == std::optional<usize>{2});
        assert(v.next_set(2) == std::optional<usize>{27});
        assert(v.next_set(27) == std::optional<usize>{});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 556;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v;
        assert(v.previous_set(36) == std::optional<usize>{});
        v.set(2);
        v.set(27);
        assert(v.previous_set(36) == std::optional<usize>{27});
        assert(v.previous_set(27) == std::optional<usize>{2});
        assert(v.previous_set(2)  == std::optional<usize>{});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 574;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v; v.set_all();
        assert(v.first_unset() == std::optional<usize>{});
        v.set(2, false);
        assert(v.first_unset() == std::optional<usize>{2});
        v.set(2);
        assert(v.first_unset() == std::optional<usize>{});
        v.set(27, false);
        assert(v.first_unset() == std::optional<usize>{27});
        BitSet<0> empty;
        assert(empty.first_unset() == std::optional<usize>{});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 591;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v; v.set_all();
        assert(v.last_unset() == std::optional<usize>{});
        v.set(2, false);
        assert(v.last_unset() == std::optional<usize>{2});
        v.set(2);
        assert(v.last_unset() == std::optional<usize>{});
        v.set(27, false);
        assert(v.last_unset() == std::optional<usize>{27});
        BitSet<0> empty;
        assert(empty.last_unset() == std::optional<usize>{});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 608;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v; v.set_all();
        assert(v.next_unset(0) == std::optional<usize>{});
        v.set(2, false);
        v.set(27, false);
        assert(v.next_unset(0) == std::optional<usize>{2});
        assert(v.next_unset(2) == std::optional<usize>{27});
        assert(v.next_unset(27) == std::optional<usize>{});
        BitSet<0> empty;
        assert(empty.next_unset(0) == std::optional<usize>{});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 624;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v; v.set_all();
        assert(v.previous_unset(0) == std::optional<usize>{});
        v.set(2, false);
        v.set(27, false);
        assert(v.previous_unset(36) == std::optional<usize>{27});
        assert(v.previous_unset(27) == std::optional<usize>{2});
        assert(v.previous_unset(2) == std::optional<usize>{});
        BitSet<0> empty;
        assert(empty.previous_unset(0) == std::optional<usize>{});
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 649;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<37, u8> v; v.set_all();
        for (auto&& bit : v.bits()) assert_eq(bit, true);
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 663;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        for (auto&& bit : v.bits()) bit = true;
        assert_eq(v.to_string(), "1111111111");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 675;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        v.fill_from([](usize i) { return i % 2 == 0; });
        assert_eq(v.to_string(), "1010101010");
        auto indices = std::ranges::to<std::vector>(v.set_bits());
        assert_eq(indices, (std::vector<usize>{0, 2, 4, 6, 8}));
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 689;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        v.fill_from([](usize i) { return i % 2 == 0; });
        assert_eq(v.to_string(), "1010101010");
        auto indices = std::ranges::to<std::vector>(v.unset_bits());
        assert_eq(indices, (std::vector<usize>{1, 3, 5, 7, 9}));
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 709;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v; v.set_all();
        assert_eq(v.to_string(), "1111111111");
        auto words = std::ranges::to<std::vector>(v.store_words());
        assert_eq(words, (std::vector<u8>{0b1111'1111, 0b0000'0011}));
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 722;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v; v.set_all();
        auto words = v.to_words();
        assert_eq(words, (std::vector<u8>{0b1111'1111, 0b0000'0011}));
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 740;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        v.fill_from([](usize i) { return i % 2 == 0; });
        auto s = v.span(1,5);
        assert_eq(s.to_string(), "0101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 755;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        v.fill_from([](usize i) { return i % 2 == 0; });
        auto s = v.span(1,5);
        assert_eq(s.to_string(), "0101");
        s.set_all();
        assert_eq(s.to_string(), "1111");
        assert_eq(v.to_string(), "1111101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 775;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        v.fill_from([](usize i) { return i % 2 == 0; });
        auto s = v.sub(1,5);
        assert_eq(s.to_string(), "0101");
        s.set_all();
        assert_eq(s.to_string(), "1111");
        assert_eq(v.to_string(), "1010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 803;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        v.fill_from([](usize i) { return i % 2 == 0; });
        BitVec<u8> left, right;
        v.split_at(5, left, right);
        assert_eq(left.to_string(), "10101");
        assert_eq(right.to_string(), "01010");
        assert_eq(v.to_string(), "1010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 826;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        v.fill_from([](usize i) { return i % 2 == 0; });
        auto [left, right] = v.split_at(5);
        assert_eq(left.to_string(), "10101");
        assert_eq(right.to_string(), "01010");
        assert_eq(v.to_string(), "1010101010");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 848;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v; v.set_all();
        BitVec<u8> dst;
        v.riffled(dst);
        assert_eq(dst.to_string(), "1010101010101010101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 863;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v; v.set_all();
        auto dst = v.riffled();
        assert_eq(dst.to_string(), "1010101010101010101");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 883;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        assert_eq(v.to_binary_string(), "0000000000");
        v.set(0);
        assert_eq(v.to_binary_string(), "1000000000");
        assert_eq(v.to_binary_string(",", "[", "]"), "[1,0,0,0,0,0,0,0,0,0]");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 904;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10, u8> v;
        assert_eq(v.to_string(), "0000000000");
        v.set(0);
        assert_eq(v.to_string(), "1000000000");
        assert_eq(v.to_string(",", "[", "]"), "[1,0,0,0,0,0,0,0,0,0]");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 921;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<10> v;
        v.fill_from([](usize i) { return i % 2 == 0; });
        assert_eq(v.to_pretty_string(), "[1,0,1,0,1,0,1,0,1,0]");
        BitVec empty;
        assert_eq(empty.to_pretty_string(), "[]");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    header_line = 949;
    test_passed = true;
    std::print(stderr, "test {}/{} ({}:{}) ... ", ++test, test_count, header_file, header_line);
    try {
        BitSet<0> v0;
        assert_eq(v0.to_hex_string(), "");
        BitSet<4> v1; v1.set_all();
        assert_eq(v1.to_hex_string(), "F");
        BitSet<5> v2; v2.set_all();
        assert_eq(v2.to_hex_string(), "F1.2");
        BitSet<8> v3;
        v3.fill_from([](usize i) { return i % 2 == 0; });
        assert_eq(v3.to_binary_string(), "10101010");
        assert_eq(v3.to_hex_string(), "AA");
    } catch (const doxy::error& failure) { handle_failure(failure.what()); }
    if (test_passed) std::println(stderr, "pass");

    // Print a summary of the tests results.
    if (fails == 0) {
        std::println(stderr, "[{}] All {} tests PASSED", header_file, test_count);
    } else {
        std::println(stderr);
        std::println(stderr, "Test FAIL summary for `{}`: Ran {} of a possible {} tests, PASSED: {}, FAILED: {}", header_file, test, test_count, test - fails, fails);
        std::print(stderr, "--------------------------------------------------------------------------------------");
        for (const auto& msg : failed_messages) std::print(stderr, "{}", msg);
    }

    // Return 1 if there were any failures, 0 otherwise.
    return fails > 0 ? 1 : 0;
}