// This file was generated by running the script `doxytest.py` to extract tests from comments in input files.
// Input file(s): `gf2.h`
// Do not edit this file manually -- it may be overwritten.
// Generated on: 2026-01-24 15:10:18

#include "../include/gf2/gf2.h"
#include <print>

int main() {
    std::println(stderr, "No test cases were found in `gf2.h`.");
}