// This file was generated by running the script `doxytest.py` to extract tests from comments in input files.
// Input file(s): `namespace.h`
// Do not edit this file manually -- it may be overwritten.
// Generated on: 2026-01-22 10:27:07

#include "../include/gf2/namespace.h"
#include <print>

int main() {
    std::println(stderr, "No test cases were found in `namespace.h`.");
}